### ISSUE TITLE
inject.toFile is executing the wrong command

### ISSUE THREAD

**Issue by SamyPesse** [1Password/op-js#125]
### Your environment

op-js version: 0.1.8

CLI version: 2.18.0

OS: Mac

## What happened?

Using `inject.toFile` doesn't work and output the file path in the output file.

It seems to be related to the `stdin: inputFile` in https://github.com/1Password/op-js/blob/main/src/index.ts#L94-L107
instead of being passed as an option.

## What did you expect to happen?

For the right command to be executed :)

## Steps to reproduce

1.

**Comment by jodyheavener** [comment]
Hey @SamyPesse! Thanks for opening this ticket. I'm trying this out on my end and haven't been able reproduce based on how I understand what you're describing. Could you provide a code sample or more details on how you are reproducing this? Thank you!

**Comment by jodyheavener** [comment]
Hi there. I'm going to close this issue due to inactivity. Please re-open or file a new issue if you feel like it persists for you.
