### ISSUE TITLE
Add support for service accounts

### ISSUE THREAD

**Issue by jodyheavener** [1Password/op-js#164]
### Summary

With [1Password Service Accounts](https://developer.1password.com/docs/service-accounts/) launched we should add support for configuring a service account with op-js.

### Use cases

- Any use case of the CLI via op-js that doesn't want to use biometrics or otherwise wants to perform actions not tied to a specific individual.
- In op-js own codebase, we can move to SA-based integration tests.

### Proposed solution

Much like [Connect env vars](https://github.com/1Password/op-js/blob/main/src/cli.ts#L260-L263), allow the user to set a service account token via env var: `OP_SERVICE_ACCOUNT_TOKEN`.

**Note**: 1Password CLI only supports a [subset of commands](https://developer.1password.com/docs/service-accounts/get-started#supported-commands) with service accounts. It may be worth trying to figure out a solution that wraps each command in a check, if a service account is being used, if the command supports it.

### Is there a workaround to accomplish this today?

Don't think so.

**Comment by dreusel** [comment]
Setting process.env['OP_SERVICE_ACCOUNT_TOKEN'] actually works for me.

**Comment by Raj123456788** [comment]
Hey @dreusel I tried to connect using the service account with process.env but it did not work. Can you please share your example in detail? Thanks

**Comment by jodyheavener** [comment]
Addressed in https://github.com/1Password/op-js/commit/bf5f9971535de0bf9ab80e4cbe60e17cbe85fdc0
