### ISSUE TITLE
Improve testing instructions

### ISSUE THREAD

**Issue by chrisdunnbirch** [1Password/op-js#6]
### Problem

It is currently difficult to figure out how to run the `yarn test:integration` suite because there are some undocumented hoops to jump through before this will work as expected.

### Suggested solution

1. Add `.env.sample` to committed files, this should include the requisite variable names with no values so that a new contributor knows which values to provide
1. Add `op run --env-file=.env --` to the start of `test:integration` package script to reduce complexity for contributors
1. Add brief instructions to `README.md` outlining requirements for running test suites (copy `.env.sample`, add account/vault values, etc)

**Comment by jodyheavener** [comment]
Closing as wontfix for now while we prioritize work.
