### ISSUE TITLE
Support Connect Server

### ISSUE THREAD

**Issue by jodyheavener** [1Password/op-js#77]
### Summary

This package currently relies on biometrics to authenticate the user, but we can also use Connect Server to interact with 1Password via the CLI. Let's support it.

### Use cases

Someone may be building something with op-js that is not intended to be tied to a specific user, but their hosted service.

### Proposed solution

Add new helper functions that can be used to pass the [environment variable](https://github.com/1Password/op-js/blob/main/src/cli.ts#L232) for this auth method to the command. Needs: `OP_CONNECT_HOST` and `OP_CONNECT_TOKEN`

### Is there a workaround to accomplish this today?

No

### References & Prior Work

- [Load secrets into config files](https://developer.1password.com/docs/cli/secrets-config-files/#optional-use-op-inject-in-production)

**Comment by parkeyparker** [comment]
It is possible to workaround this by passing in the relevant environment variables to the script itself. See this snippet for where the env vars are brought in: https://github.com/1Password/op-js/blob/main/src/cli.ts#L248-L257
